type Screen = "home" | "services" | "rfq" | "tablet" | "mobile";
const hero = "https://www.gcnusantara.com/assets/generated/hero-supply-trading-construction-001.jpg";

function Chrome(){return <div className="flex h-[7%] items-center gap-2 border-b border-slate-200 bg-white px-3"><i className="h-2 w-2 rounded-full bg-rose-400"/><i className="h-2 w-2 rounded-full bg-amber-400"/><i className="h-2 w-2 rounded-full bg-emerald-400"/><i className="ml-2 h-3 flex-1 rounded-full bg-slate-100"/></div>}

export default function GcnSitePreview({screen="home"}:{screen?:Screen}){
 const mobile=screen==="mobile";
 const tablet=screen==="tablet";
 const compact=mobile||tablet;
 const deviceClass=mobile?"w-[46%] rounded-[26px] border-[6px] border-slate-950":tablet?"w-[76%] rounded-[22px] border-[5px] border-slate-900":"w-full rounded-2xl border border-slate-200";
 return <div className="h-full bg-gradient-to-br from-slate-100 via-white to-blue-50 p-[4%]">
  <div className={`mx-auto h-full overflow-hidden bg-[#07192d] shadow-[0_30px_80px_-35px_rgba(7,25,45,.7)] ${deviceClass}`}>
   {!compact&&<Chrome/>}
   <div className={`${compact?"h-full":"h-[93%]"} relative overflow-hidden text-white`}>
    <div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${hero})`}}/><div className="absolute inset-0 bg-[#07192d]/75"/>
    <div className="relative z-10 flex h-[14%] items-center justify-between px-[6%]"><b className="text-[clamp(7px,1.1vw,15px)]">GCN</b>{compact?<span className="text-[clamp(8px,1vw,14px)]">☰</span>:<div className="flex items-center gap-[3.2%] text-[clamp(4px,.5vw,7px)]"><span>Beranda</span><span>Layanan Kami</span><span>Karya Kami</span><span>Dampak untuk Klien</span><span>Perusahaan Kami</span><span>Kerja Sama</span><span className="border border-white/60 px-2 py-1">Ajukan Penawaran</span></div>}</div>
    {screen==="rfq"?<div className="relative z-10 grid h-[86%] grid-cols-2 items-center gap-[7%] px-[7%]"><div><p className="text-[clamp(4px,.52vw,7px)] font-bold uppercase tracking-[.18em] text-[#4fb4ff]">Request for Quotation</p><h3 className="mt-[4%] text-[clamp(14px,2.2vw,31px)] font-semibold leading-tight">Ajukan kebutuhan supply, trading atau konstruksi.</h3><p className="mt-[4%] text-[clamp(5px,.6vw,8px)] text-white/70">Tim GCN akan meninjau spesifikasi dan menghubungi Anda untuk proses penawaran.</p></div><div className="rounded-xl border border-white/20 bg-white/10 p-[7%] backdrop-blur">{["Nama / Perusahaan","Email / WhatsApp","Kategori kebutuhan","Deskripsi / spesifikasi"].map((x,i)=><div key={x} className={`mb-[5%] rounded border border-white/20 bg-white/10 px-3 py-2 text-[clamp(4px,.5vw,7px)] text-white/55 ${i===3?"h-14":""}`}>{x}</div>)}<div className="w-1/2 bg-white px-3 py-2 text-center text-[clamp(4px,.5vw,7px)] font-bold text-[#07192d]">Kirim RFQ</div></div></div>
    :screen==="services"?<div className="relative z-10 h-[86%] px-[7%] py-[5%]"><p className="text-[clamp(4px,.52vw,7px)] font-bold uppercase tracking-[.18em] text-[#4fb4ff]">Layanan Kami</p><h3 className="mt-[3%] max-w-[75%] text-[clamp(14px,2.1vw,29px)] font-semibold leading-tight">Kapabilitas supply, trading dan pelaksanaan konstruksi.</h3><div className="mt-[5%] grid grid-cols-3 gap-[3%]">{["Product Supply","Wholesale Trading","Construction Execution"].map(x=><div key={x} className="rounded-lg border border-white/20 bg-white/10 p-[8%] backdrop-blur"><b className="text-[clamp(6px,.75vw,10px)]">{x}</b><p className="mt-[5%] text-[clamp(4px,.5vw,7px)] leading-relaxed text-white/60">Scope disesuaikan dengan proyek, spesifikasi dan kebutuhan klien.</p></div>)}</div></div>
    :<div className="relative z-10 flex h-[86%] items-center px-[7%] pb-[7%]"><div className={`${mobile?"max-w-full":"max-w-[78%]"}`}><p className="text-[clamp(4px,.55vw,8px)] font-semibold uppercase tracking-[.16em] text-[#4fb4ff]">Supply | Trading | Konstruksi</p><h3 className="mt-[5%] text-[clamp(15px,2.7vw,38px)] font-semibold leading-[1.02]">Solusi supply, trading dan konstruksi yang tepat untuk bisnis Anda.</h3><p className="mt-[5%] max-w-[75%] text-[clamp(5px,.65vw,9px)] leading-relaxed text-white/70">PT Gega Cahaya Nusantara mendukung kebutuhan klien melalui supply produk, perdagangan grosir dan pelaksanaan konstruksi.</p><div className="mt-[6%] flex gap-[3%]"><span className="bg-white px-[5%] py-[3%] text-[clamp(4px,.5vw,7px)] font-bold uppercase tracking-widest text-[#07192d]">Jelajahi bisnis kami</span><span className="border border-white/50 px-[5%] py-[3%] text-[clamp(4px,.5vw,7px)] uppercase tracking-widest">Ajukan Penawaran</span></div></div></div>}
   </div>
  </div>
 </div>
}
