import type { PortfolioItem } from "@/content/portfolio";

function Chrome() {
  return <div className="flex h-[7%] items-center gap-[1.1%] border-b border-slate-200 bg-white px-[2%]"><i className="aspect-square w-[1.5%] rounded-full bg-rose-400"/><i className="aspect-square w-[1.5%] rounded-full bg-amber-400"/><i className="aspect-square w-[1.5%] rounded-full bg-emerald-400"/><i className="ml-[1%] h-[38%] flex-1 rounded-full bg-slate-100"/></div>;
}
function Bars({purple=false}:{purple?:boolean}) { return <div className="flex h-full items-end gap-[4%]">{[38,58,49,72,64,83,96].map((h,i)=><i key={i} className={purple?"flex-1 rounded-t bg-violet-500":"flex-1 rounded-t bg-blue-500"} style={{height:`${h}%`}}/>)}</div> }
function Metric({a,b,accent="text-blue-700"}:{a:string;b:string;accent?:string}) { return <div className="min-w-0 rounded-[5px] border border-slate-200 bg-white p-[6%] shadow-sm"><div className="truncate text-[clamp(3px,.48vw,7px)] uppercase text-slate-400">{a}</div><div className={`truncate text-[clamp(5px,.82vw,12px)] font-bold ${accent}`}>{b}</div></div> }

function SakaPlatform(){return <div className="h-full bg-gradient-to-br from-[#eaf2fb] to-white p-[4%]"><div className="relative mx-auto h-full max-w-[1050px]">
  <div className="absolute left-[3%] top-[5%] h-[82%] w-[76%] overflow-hidden rounded-[18px] border border-slate-200 bg-white shadow-2xl"><Chrome/><div className="flex h-[93%]"><aside className="w-[21%] bg-[#071e3b] p-[4%] text-white"><b className="text-[clamp(6px,1vw,14px)]">SAKA</b><div className="mt-[18%] space-y-[9%] text-[clamp(3px,.55vw,8px)] text-white/60"><p>Overview</p><p>Leads</p><p>Projects</p><p>Proposals</p><p>Clients</p><p>Invoices</p><p>Insights</p></div></aside><main className="flex-1 bg-[#f8fafc] p-[4%]"><p className="text-[clamp(7px,1.2vw,17px)] font-bold text-slate-900">Digital Business Command Center</p><p className="text-[clamp(3px,.52vw,7px)] text-slate-400">Website leads · portfolio · content · internal operations</p><div className="mt-[5%] grid grid-cols-4 gap-[2%]"><Metric a="Website Leads" b="42"/><Metric a="Open Projects" b="8"/><Metric a="Proposals" b="12"/><Metric a="Content" b="24"/></div><div className="mt-[4%] grid h-[48%] grid-cols-[1.4fr_1fr] gap-[3%]"><div className="rounded-lg border bg-white p-[5%]"><b className="text-[clamp(4px,.6vw,9px)]">Lead & Project Activity</b><div className="mt-[7%] h-[70%]"><Bars/></div></div><div className="space-y-[5%]"><div className="h-[47%] rounded-lg border bg-white p-[7%] text-[clamp(4px,.6vw,9px)] font-semibold">AI Sales Assistant<div className="mt-[8%] rounded bg-blue-50 p-[6%] text-[clamp(3px,.48vw,7px)] font-normal text-slate-500">New inquiry qualified → Discovery call</div></div><div className="h-[47%] rounded-lg border bg-white p-[7%] text-[clamp(4px,.6vw,9px)] font-semibold">Content Pipeline<div className="mt-[8%] h-[4px] rounded bg-blue-500"/><div className="mt-[8%] h-[4px] w-2/3 rounded bg-cyan-400"/></div></div></div></main></div></div>
  <div className="absolute bottom-[3%] right-[1%] h-[62%] w-[27%] rotate-2 rounded-[20px] border bg-white p-[3%] shadow-2xl"><b className="text-[clamp(5px,.75vw,10px)] text-blue-700">SAKA Workspace</b><p className="mt-[5%] text-[clamp(3px,.48vw,7px)] text-slate-400">Internal project overview</p><div className="mt-[10%] grid grid-cols-2 gap-[6%]"><Metric a="Leads" b="42"/><Metric a="Projects" b="8"/><Metric a="Tasks" b="31"/><Metric a="Pipeline" b="Active"/></div><div className="mt-[10%] h-[28%]"><Bars/></div></div>
</div></div>}

function GcnErp(){return <div className="h-full bg-gradient-to-br from-[#eef4fb] to-white p-[4%]"><div className="relative mx-auto h-full max-w-[1050px]">
 <div className="absolute left-[2%] top-[4%] h-[88%] w-[82%] overflow-hidden rounded-[18px] border border-slate-200 bg-white shadow-2xl"><Chrome/><div className="flex h-[93%]"><aside className="w-[22%] bg-slate-950 p-[4%] text-white"><b className="text-[clamp(5px,.9vw,13px)]">GCN MANAGEMENT</b><div className="mt-[16%] space-y-[7%] text-[clamp(3px,.52vw,7px)] text-white/60"><p>Data Intelligence</p><p>Sales</p><p>Operations & Projects</p><p>Finance & Accounting</p><p>Documents & Archive</p><p>Administration</p></div></aside><main className="flex-1 bg-[#f8fafc] p-[4%]"><p className="text-[clamp(7px,1.1vw,16px)] font-bold">GCN Intelligence Command Center</p><p className="text-[clamp(3px,.5vw,7px)] text-slate-400">Commercial · projects · cashflow · exceptions</p><div className="mt-[4%] rounded-lg border bg-white p-[4%]"><div className="flex items-center gap-[3%]"><span className="rounded-lg bg-slate-950 px-[3%] py-[2%] text-[clamp(4px,.58vw,8px)] text-white">GCN AI</span><span className="text-[clamp(3px,.5vw,7px)] text-slate-500">Deal mana yang harus dikejar?</span></div></div><div className="mt-[4%] grid grid-cols-4 gap-[2%]"><Metric a="Forecast Revenue" b="Rp 2,8 M"/><Metric a="Opportunities" b="18"/><Metric a="Active Projects" b="11"/><Metric a="Overdue AR" b="Rp 340 Jt"/></div><div className="mt-[4%] grid h-[40%] grid-cols-[1.3fr_1fr] gap-[3%]"><div className="rounded-lg border bg-white p-[5%]"><b className="text-[clamp(4px,.6vw,8px)]">Business Pulse</b><div className="mt-[8%] h-[68%]"><Bars/></div></div><div className="rounded-lg border bg-white p-[5%]"><b className="text-[clamp(4px,.6vw,8px)]">Needs Attention</b><div className="mt-[8%] space-y-[6%] text-[clamp(3px,.46vw,7px)] text-slate-500"><p className="rounded bg-amber-50 p-[4%]">3 quotations need approval</p><p className="rounded bg-red-50 p-[4%]">2 invoices overdue</p><p className="rounded bg-blue-50 p-[4%]">4 projects in execution</p></div></div></div></main></div></div>
 <div className="absolute bottom-[2%] right-[1%] h-[57%] w-[25%] rounded-[18px] border bg-white p-[3%] shadow-2xl"><b className="text-[clamp(5px,.7vw,10px)] text-blue-700">Business Modules</b><div className="mt-[8%] space-y-[5%] text-[clamp(3px,.5vw,7px)]"><p className="rounded-lg border p-[6%]">Sales</p><p className="rounded-lg border p-[6%]">Operations & Projects</p><p className="rounded-lg border p-[6%]">Finance & Accounting</p><p className="rounded-lg border p-[6%]">Documents & Archive</p></div></div>
</div></div>}

function DbiErp(){return <div className="h-full bg-gradient-to-br from-[#f5eef6] to-white p-[4%]"><div className="relative mx-auto h-full max-w-[1050px]">
 <div className="absolute left-[2%] top-[4%] h-[88%] w-[82%] overflow-hidden rounded-[18px] border border-violet-100 bg-white shadow-2xl"><Chrome/><div className="flex h-[93%]"><aside className="w-[22%] bg-[#351642] p-[4%] text-white"><b className="text-[clamp(6px,.95vw,13px)]">DERMA BEAUTY</b><p className="mt-[4%] text-[clamp(3px,.45vw,6px)] text-violet-200">ERP / MIS</p><div className="mt-[15%] space-y-[6%] text-[clamp(3px,.5vw,7px)] text-white/65"><p>Commercial</p><p>NPD / R&D</p><p>Production</p><p>Inventory & Supply Chain</p><p>Quality & Regulatory</p><p>Finance</p><p>People & Learning</p></div></aside><main className="flex-1 bg-[#fbfafc] p-[4%]"><div className="flex justify-between"><div><p className="text-[clamp(7px,1.1vw,16px)] font-bold">Data Intelligence</p><p className="text-[clamp(3px,.5vw,7px)] text-slate-400">Cross-functional management intelligence</p></div><span className="rounded-full bg-emerald-50 px-[3%] py-[1.5%] text-[clamp(3px,.45vw,6px)] text-emerald-700">Scope ALL</span></div><div className="mt-[4%] grid grid-cols-3 gap-[2%]"><Metric a="Revenue" b="Rp 15,7 M" accent="text-violet-700"/><Metric a="Collection Rate" b="84,2%" accent="text-violet-700"/><Metric a="Outstanding AR" b="Rp 2,4 M" accent="text-violet-700"/><Metric a="Customers" b="86" accent="text-violet-700"/><Metric a="Production Orders" b="128" accent="text-violet-700"/><Metric a="Inventory Value" b="Rp 4,2 M" accent="text-violet-700"/></div><div className="mt-[4%] grid h-[43%] grid-cols-2 gap-[3%]"><div className="rounded-lg border bg-white p-[5%]"><b className="text-[clamp(4px,.58vw,8px)]">Tren Performa Bisnis</b><div className="mt-[7%] h-[68%]"><Bars purple/></div></div><div className="rounded-lg border bg-white p-[5%]"><b className="text-[clamp(4px,.58vw,8px)]">Distribusi Pipeline Bisnis</b><div className="mt-[8%] flex h-[60%] items-center justify-center"><div className="aspect-square h-full rounded-full border-[clamp(5px,1vw,13px)] border-violet-500 border-b-fuchsia-200 border-r-purple-300"/></div></div></div></main></div></div>
 <div className="absolute bottom-[2%] right-[1%] h-[58%] w-[25%] rotate-1 rounded-[18px] border border-violet-100 bg-white p-[3%] shadow-2xl"><b className="text-[clamp(5px,.72vw,10px)] text-violet-700">Manufacturing Pulse</b><div className="mt-[9%] grid grid-cols-2 gap-[6%]"><Metric a="NPD" b="14" accent="text-violet-700"/><Metric a="Batches" b="128" accent="text-violet-700"/><Metric a="QC Release" b="94%" accent="text-violet-700"/><Metric a="Returns" b="2.3%" accent="text-violet-700"/></div><p className="mt-[10%] text-[clamp(3px,.48vw,7px)] font-semibold">Production & Quality Trend</p><div className="mt-[5%] h-[28%]"><Bars purple/></div></div>
</div></div>}

function GcnWebsite(){return <div className="h-full bg-gradient-to-br from-slate-100 via-white to-cyan-50 p-[4%]"><div className="relative mx-auto h-full max-w-[1050px]">
 <div className="absolute left-[2%] top-[5%] h-[82%] w-[77%] overflow-hidden rounded-[18px] border-[6px] border-slate-950 bg-white shadow-2xl"><Chrome/><div className="relative h-[93%] overflow-hidden bg-[#07192d] text-white"><div className="flex h-[16%] items-center justify-between px-[5%]"><b className="text-[clamp(6px,1vw,14px)]">GCN</b><div className="flex gap-[8%] text-[clamp(3px,.5vw,7px)] text-white/60"><span>Company</span><span>Services</span><span>Industries</span><span>Projects</span><span>RFQ</span></div></div><div className="relative h-[84%] overflow-hidden px-[6%] py-[8%]"><div className="absolute inset-0 bg-gradient-to-br from-[#0b2944] via-[#174866] to-[#9a633d] opacity-95"/><div className="relative z-10 max-w-[65%]"><p className="text-[clamp(3px,.5vw,7px)] font-semibold text-cyan-300">SUPPLY | TRADING | CONSTRUCTION</p><h3 className="mt-[4%] text-[clamp(11px,2vw,28px)] font-bold leading-tight">Solusi supply, trading dan konstruksi yang tepat untuk bisnis Anda.</h3><p className="mt-[4%] text-[clamp(4px,.58vw,8px)] text-white/65">Private sector · public procurement · construction · aviation supply</p><div className="mt-[6%] flex gap-[3%]"><span className="bg-white px-[5%] py-[3%] text-[clamp(3px,.5vw,7px)] font-bold text-slate-900">JELAJAHI BISNIS</span><span className="border border-white/50 px-[5%] py-[3%] text-[clamp(3px,.5vw,7px)]">AJUKAN PENAWARAN</span></div></div></div></div></div>
 <div className="absolute bottom-[2%] right-[1%] h-[65%] w-[25%] rounded-[22px] border-[6px] border-slate-950 bg-[#07192d] p-[5%] text-white shadow-2xl"><div className="mx-auto h-[2%] w-[28%] rounded bg-white/60"/><b className="mt-[15%] block text-[clamp(5px,.72vw,10px)]">GCN</b><p className="mt-[22%] text-[clamp(3px,.45vw,6px)] text-cyan-300">TRUSTED BUSINESS PARTNER</p><p className="mt-[5%] text-[clamp(7px,1.15vw,16px)] font-bold">Supply, Trading & Construction</p><div className="mt-[12%] h-[25%] rounded bg-gradient-to-br from-cyan-900 to-amber-700"/></div>
</div></div>}

export default function PortfolioVisual({item}:{item:PortfolioItem;large?:boolean}){
 if(item.slug==="gcn-management-system-erp") return <GcnErp/>;
 if(item.slug==="dbi-erp-mis") return <DbiErp/>;
 if(item.slug==="gcn-corporate-website") return <GcnWebsite/>;
 return <SakaPlatform/>;
}
