import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ExternalLink } from "lucide-react";
import { publishedPortfolio, getPortfolioBySlug } from "@/content/portfolio";
import ProjectPreview from "@/components/portfolio/ProjectPreview";
import ProjectInterfaceGallery from "@/components/portfolio/ProjectInterfaceGallery";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return publishedPortfolio.map((p) => ({ slug: p.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const item = getPortfolioBySlug(slug); if (!item) return { robots: { index: false, follow: false } }; return { title: item.title, description: item.problem, alternates: { canonical: `/portfolio/${item.slug}` } }; }
const privacyNote = "Tampilan berasal dari sistem yang diimplementasikan. Data operasional telah dianonimkan atau diganti dengan data demonstrasi untuk melindungi kerahasiaan klien.";

export default async function PortfolioDetailPage({ params }: Props) {
 const { slug } = await params; const item = getPortfolioBySlug(slug); if (!item) notFound();
 return <>
 <section className="border-b border-line bg-soft"><div className="container-page py-9 sm:py-12 lg:py-20"><div className="mb-4 flex flex-wrap items-center gap-2.5"><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-accent">Proyek Nyata</span><span className="rounded-full border border-line bg-white px-3 py-1 text-xs font-medium text-muted">{item.availability}</span></div><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-accent sm:text-sm">{item.client}</p><h1 className="max-w-4xl text-3xl font-bold tracking-tight text-ink sm:text-4xl lg:text-5xl">{item.title}</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted sm:text-base lg:text-lg">{item.projectType} · {item.industry}</p></div></section>
 <section className="py-7 sm:py-9 lg:py-14"><div className="container-page"><div className="relative aspect-[4/3] w-full overflow-hidden rounded-xl2 border border-line bg-soft shadow-[0_22px_60px_-28px_rgba(7,21,46,0.38)] sm:aspect-[16/10]"><ProjectPreview item={item}/></div><p className="mt-3 max-w-4xl text-[11px] leading-relaxed text-muted sm:text-xs">{privacyNote}</p></div></section>
 <section className="section-y pt-5 sm:pt-7 lg:pt-10"><div className="container-page space-y-12 sm:space-y-14 lg:space-y-20">
 <div className="grid gap-10 lg:grid-cols-3 lg:gap-12"><div className="space-y-8 sm:space-y-10 lg:col-span-2"><section><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">01 · Gambaran Proyek</p><h2 className="mb-3 text-xl font-semibold text-ink sm:text-2xl">Apa yang Dibangun?</h2><p className="text-sm leading-relaxed text-muted sm:text-base">{item.solution}</p></section><section><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">02 · Masalah Bisnis</p><h2 className="mb-3 text-xl font-semibold text-ink sm:text-2xl">Masalah yang Ingin Diselesaikan</h2><p className="text-sm leading-relaxed text-muted sm:text-base">{item.problem}</p></section></div><aside className="space-y-4"><div className="rounded-xl2 border border-line bg-soft p-5 sm:p-6"><h3 className="mb-3 text-sm font-semibold text-muted">Status</h3><p className="text-sm font-semibold text-ink">{item.availability}</p><p className="mt-1 text-xs text-muted">{item.projectType}</p></div>{item.liveUrl&&<a href={item.liveUrl} target="_blank" rel="noreferrer" className="flex min-h-12 w-full items-center justify-center gap-2 rounded-full border border-accent px-6 py-3.5 text-sm font-semibold text-accent hover:bg-accent hover:text-white">Lihat Project<ExternalLink size={16}/></a>}</aside></div>
 <section><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">03 · Ruang Lingkup</p><h2 className="mb-5 text-xl font-semibold text-ink sm:text-2xl">Bagian Sistem yang Dibangun</h2><div className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-3">{item.modules.map((m)=><div key={m} className="rounded-xl border border-line bg-soft px-4 py-3.5 text-sm font-medium text-ink">{m}</div>)}</div></section>
 <section><div className="mb-5 sm:mb-7"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">04 · Tampilan Sistem</p><h2 className="text-xl font-semibold text-ink sm:text-2xl">Lihat Interface yang Diimplementasikan</h2><p className="mt-2.5 max-w-3xl text-sm leading-relaxed text-muted">Tampilan mengikuti sistem yang benar-benar dibangun. Klik gambar untuk melihat detail interface.</p></div><ProjectInterfaceGallery item={item}/><p className="mt-4 max-w-4xl text-[11px] leading-relaxed text-muted sm:text-xs">{privacyNote}</p></section>
 <section className="grid gap-9 lg:grid-cols-2"><div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">05 · Teknologi</p><h2 className="mb-4 text-xl font-semibold text-ink sm:text-2xl">Teknologi yang Digunakan</h2><div className="flex flex-wrap gap-2">{item.technology.map((t)=><span key={t} className="rounded-full bg-soft px-3 py-2 text-xs font-medium text-ink">{t}</span>)}</div></div><div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-accent">06 · Hasil</p><h2 className="mb-3 text-xl font-semibold text-ink sm:text-2xl">Hasil Implementasi</h2><p className="text-sm leading-relaxed text-muted sm:text-base">{item.result}</p></div></section>
 <section className="rounded-xl2 bg-navy px-5 py-7 text-white sm:px-7 sm:py-8 lg:px-10"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-white/60">Langkah Berikutnya</p><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold sm:text-2xl">Punya masalah bisnis yang mirip?</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/70">Ceritakan proses yang ingin dirapikan. Kami bantu diskusikan solusi yang sesuai kebutuhan Anda.</p></div><Link href="/contact" className="inline-flex min-h-12 w-full shrink-0 items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-navy sm:w-auto">Konsultasikan Kebutuhan<ArrowRight size={16}/></Link></div></section>
 </div></section></>;
}
